# Copyright 2026 The semviews authors.
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
"""Rephrased predicates: the same question asked in different words (workload W_R).

A seeded random sample of predicates from a pool is reworded once by the judge model, taped
through TapedLM. Output: configs/predicates/<dataset>_rephrased.yaml with ids `rw_<id>` and a
`rephrase_of` field. The originals are untouched; the reworded predicates are labeled into a
separate tape (build_tape --pool <dataset>_rephrased --tag rw).

    python -m semviews.adapters.lotus.rephrase --dataset reviews --n 15
"""

from __future__ import annotations

import argparse
import logging
import os
import re

import lotus
import numpy as np
import yaml
from dotenv import load_dotenv

from semviews.adapters.lotus.taped_lm import TapedLM

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))

SYSTEM = (
    "You rewrite yes/no filter conditions that an analyst applies to text records. Rewrite the given "
    "condition so that it asks for the same thing in different words, the way a different analyst might "
    "phrase it. Keep the meaning; do not narrow or broaden it. Keep the placeholder {text} exactly once, "
    "where the record goes. Reply with the rewritten condition only."
)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset", required=True)
    ap.add_argument("--n", type=int, default=15)
    ap.add_argument("--seed", type=int, default=0)
    a = ap.parse_args()
    load_dotenv(os.path.join(ROOT, ".env"))
    lotus.settings.configure(enable_cache=False)
    logging.getLogger("lotus").setLevel(logging.ERROR)
    models_cfg = yaml.safe_load(open(os.path.join(ROOT, "configs", "models.yaml")))
    pool = yaml.safe_load(open(os.path.join(ROOT, "configs", "predicates", f"{a.dataset}.yaml")))
    preds = pool["predicates"]
    pick = sorted(np.random.default_rng(a.seed).choice(len(preds), size=min(a.n, len(preds)), replace=False))
    lm = TapedLM.for_alias(models_cfg["judge"], models_cfg, tape_path=os.path.join(ROOT, "data", "tapes", "judge.sqlite"),
                           max_batch_size=16)
    msgs = [[{"role": "system", "content": SYSTEM}, {"role": "user", "content": preds[i]["langex"]}] for i in pick]
    outs = lm(msgs).outputs
    out = []
    for i, txt in zip(pick, outs):
        txt = re.sub(r"\{\s*text\s*\}", "{text}", str(txt).strip().strip('"').strip())  # formatting only
        if txt.count("{text}") != 1:
            logging.warning("skipping %s: placeholder missing in %r", preds[i]["id"], txt)
            continue
        out.append({"id": f"rw_{preds[i]['id']}", "langex": txt, "rephrase_of": preds[i]["id"], "level": preds[i].get("level")})
    doc = {k: v for k, v in pool.items() if k != "predicates"}
    doc["predicates"] = out
    path = os.path.join(ROOT, "configs", "predicates", f"{a.dataset}_rephrased.yaml")
    with open(path, "w") as f:
        f.write("# Generated by semviews.adapters.lotus.rephrase (judge model, temperature 0). Do not edit.\n")
        yaml.safe_dump(doc, f, sort_keys=False, width=200)
    for p in out:
        print(p["rephrase_of"], "->", p["langex"])


if __name__ == "__main__":
    main()
